version: 1
formatters:
  simple:
    format: '[%(name)8s] %(message)s'
  full:
    format: '%(asctime)s [%(name)8s] %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  logfile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: full
    filename: 'log/app.log'
    backupCount: 2
    mode: 'w'
  broadcastfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: full
    filename: 'log/broadcastdata.log'
    mode: 'w'
loggers:
  app:
    level: DEBUG
    handlers: [logfile, console]
    propagate: no
  broadcast:
    level: DEBUG
    handlers: [broadcastfile]
    propagate: no
root:
  level: DEBUG
  handlers: [logfile, console]
